app:
  scheduler:
    enable: false
    worker-schedule-updater:
      enable: false
      interval: 15s
    mail-sender:
      enable: false
      interval: 15s
  jwt:
    token:
      secret:
        key: ${JWT_TOKEN}
      expiration: 360000000


spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/barbershop
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      order_inserts: true
      generate_statistics: true
      order_updates: true
      jdbc:
        batch_size: 500
    open-in-view: false
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui
